# Generated by Django 4.2.7 on 2023-11-26 23:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wtknowledgebase.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('card', wagtail.blocks.StructBlock([('header_title', wagtail.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.blocks.StructBlock([('class_name', wagtail.blocks.CharBlock(required=False)), ('cells', wagtail.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))])), ('jumbotron', wagtail.blocks.StructBlock([('extra_class', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('card', wagtail.blocks.StructBlock([('header_title', wagtail.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.blocks.StructBlock([('class_name', wagtail.blocks.CharBlock(required=False)), ('cells', wagtail.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))]))]))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('card', wagtail.blocks.StructBlock([('header_title', wagtail.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.blocks.StructBlock([('class_name', wagtail.blocks.CharBlock(required=False)), ('cells', wagtail.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))])), ('jumbotron', wagtail.blocks.StructBlock([('extra_class', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('card', wagtail.blocks.StructBlock([('header_title', wagtail.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('page', wagtail.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.blocks.StructBlock([('class_name', wagtail.blocks.CharBlock(required=False)), ('cells', wagtail.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))]))]))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
